language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
before_install:
  - sudo apt-get install clamav-daemon clamav-freshclam clamav-unofficial-sigs
  - sudo freshclam
  - sudo service clamav-daemon start
script: rake
