language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
before_install: "sudo ./test/ci-setup.sh"
env:
  - CLAMD_UNIX_SOCKET=/var/run/clamav/clamd.ctl
script: rake
